# org.gradle.java.home=/opt/homebrew/Cellar/openjdk@21/21.0.10/libexec/openjdk.jdk/Contents/Home
org.gradle.jvmargs=-Xmx2g

# Project
projectVersion=0.1.0
javaVersion=21

# Spring
springBootVersion=3.4.5
springDependencyManagementVersion=1.1.7
springdocVersion=2.8.5

# Lombok
lombokVersion=1.18.34

# Logstash
logstashVersion=7.4

# Apache Commons
commonsLang3Version=3.14.0

# Azure
azureIdentityVersion=1.13.0
azureStorageBlobVersion=12.27.0
